name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
          Import-Module PSScriptAnalyzer

      - name: Lint PowerShell
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./src -Recurse -Severity Warning,Error

      - name: Smoke Test
        shell: pwsh
        run: |
          if (-not (Test-Path "$env:WINDIR\System32\scrnsave.scr")) { exit 1 }
          Write-Host "scrnsave.scr vorhanden: OK"
