name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  make-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip artifact
        shell: pwsh
        run: |
          Compress-Archive -Path src/TurnOffScreen.ps1 -DestinationPath planet-saver-scrnsave.zip -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: planet-saver-scrnsave.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
